/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Accessories/Index': RouteRecordInfo<'/Accessories/Index', '/Accessories/Index', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/login-2': RouteRecordInfo<'/auth/login-2', '/auth/login-2', Record<never, never>, Record<never, never>>,
    '/auth/login-3': RouteRecordInfo<'/auth/login-3', '/auth/login-3', Record<never, never>, Record<never, never>>,
    '/auth/signup-1': RouteRecordInfo<'/auth/signup-1', '/auth/signup-1', Record<never, never>, Record<never, never>>,
    '/auth/signup-2': RouteRecordInfo<'/auth/signup-2', '/auth/signup-2', Record<never, never>, Record<never, never>>,
    '/auth/signup-3': RouteRecordInfo<'/auth/signup-3', '/auth/signup-3', Record<never, never>, Record<never, never>>,
    '/BrandModels/Index': RouteRecordInfo<'/BrandModels/Index', '/BrandModels/Index', Record<never, never>, Record<never, never>>,
    '/Brands/Index': RouteRecordInfo<'/Brands/Index', '/Brands/Index', Record<never, never>, Record<never, never>>,
    '/BusinessSectors/Index': RouteRecordInfo<'/BusinessSectors/Index', '/BusinessSectors/Index', Record<never, never>, Record<never, never>>,
    '/Categories/Index': RouteRecordInfo<'/Categories/Index', '/Categories/Index', Record<never, never>, Record<never, never>>,
    '/Countries/Index': RouteRecordInfo<'/Countries/Index', '/Countries/Index', Record<never, never>, Record<never, never>>,
    '/error/page-1': RouteRecordInfo<'/error/page-1', '/error/page-1', Record<never, never>, Record<never, never>>,
    '/error/page-2': RouteRecordInfo<'/error/page-2', '/error/page-2', Record<never, never>, Record<never, never>>,
    '/error/page-3': RouteRecordInfo<'/error/page-3', '/error/page-3', Record<never, never>, Record<never, never>>,
    '/error/page-4': RouteRecordInfo<'/error/page-4', '/error/page-4', Record<never, never>, Record<never, never>>,
    '/error/page-5': RouteRecordInfo<'/error/page-5', '/error/page-5', Record<never, never>, Record<never, never>>,
    '/ModelVersions/Index': RouteRecordInfo<'/ModelVersions/Index', '/ModelVersions/Index', Record<never, never>, Record<never, never>>,
    '/Users/Index': RouteRecordInfo<'/Users/Index', '/Users/Index', Record<never, never>, Record<never, never>>,
    '/VehicleColors/Index': RouteRecordInfo<'/VehicleColors/Index', '/VehicleColors/Index', Record<never, never>, Record<never, never>>,
    '/VehicleConditions/Index': RouteRecordInfo<'/VehicleConditions/Index', '/VehicleConditions/Index', Record<never, never>, Record<never, never>>,
    '/VehicleDoors/Index': RouteRecordInfo<'/VehicleDoors/Index', '/VehicleDoors/Index', Record<never, never>, Record<never, never>>,
    '/VehicleFuelType/Index': RouteRecordInfo<'/VehicleFuelType/Index', '/VehicleFuelType/Index', Record<never, never>, Record<never, never>>,
    '/Vehicles/Create': RouteRecordInfo<'/Vehicles/Create', '/Vehicles/Create', Record<never, never>, Record<never, never>>,
    '/Vehicles/Index': RouteRecordInfo<'/Vehicles/Index', '/Vehicles/Index', Record<never, never>, Record<never, never>>,
    '/Vehicles/Show': RouteRecordInfo<'/Vehicles/Show', '/Vehicles/Show', Record<never, never>, Record<never, never>>,
    '/VehicleStatus/Index': RouteRecordInfo<'/VehicleStatus/Index', '/VehicleStatus/Index', Record<never, never>, Record<never, never>>,
    '/VehicleTransmissions/Index': RouteRecordInfo<'/VehicleTransmissions/Index', '/VehicleTransmissions/Index', Record<never, never>, Record<never, never>>,
    '/VehicleType/Index': RouteRecordInfo<'/VehicleType/Index', '/VehicleType/Index', Record<never, never>, Record<never, never>>,
  }
}
